### ISSUE TITLE
Trivy scan unpublished image

### ISSUE THREAD

**Issue by kpenfound** [jpadams/daggerverse#2]
Containers created by Dagger which have not been published do not have a ref, and so when we get the ref here https://github.com/jpadams/daggerverse/blob/main/trivy/main.go#L62 and use it here https://github.com/jpadams/daggerverse/blob/main/trivy/main.go#L64 it creates an invalid path.

We should check write the tarball to a static string instead so that it doesn't depend on the ref

**Comment by jpadams** [comment]
fixed here
https://github.com/jpadams/daggerverse/commit/dce5436fb7dea3e6283557c9b50c7e077d524653
